## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import os
import glob

webrtc_code_path = os.environ['WEBRTC_SRC_DIR']
webrtc_lib_path = os.path.join(webrtc_code_path, 'out', 'Static', 'obj')
webrtc_absl_path = os.path.join(webrtc_code_path, 'third_party', 'abseil-cpp')
def configure(conf):
    conf.env['ENABLE_webrtc'] = conf.check(
    mandatory=True,
    libpath = [webrtc_lib_path],
    includes = [
        webrtc_code_path,
        webrtc_absl_path],
    lib='webrtc',
    uselib_store = 'libwebrtc')
    conf.env.append_value("CXXFLAGS", [
    "-std=c++17",
    "-I" + webrtc_lib_path,
    "-I" + webrtc_absl_path,
    "-Wno-unused-const-variable",
    "-Wno-unused-private-field",
    "-Wno-tautological-bitwise-compare",
    "-Wno-deprecated-declarations",
    "-Wno-unused-variable",
    "-fno-permissive",
    "-Wno-error",
    ])

def build(bld):
    env = bld.env
    sim = bld.create_ns3_module('SCION', ['core', 'internet', 'network', 'applications'])

    sim.env.append_value("CXXFLAGS", [
      "-D__STDC_CONSTANT_MACROS",
      "-DWEBRTC_POSIX",
      "-DWEBRTC_LINUX",
      ])
    sim.env.append_value("LIB", ["webrtc"])
    sim.use.append("libwebrtc")

    # Define the base directory for model files
    model_dir = os.path.join(bld.path.abspath(), 'model')

    # Find all .cc files
    cc_files = [os.path.relpath(path, bld.path.abspath()) for path in glob.glob(model_dir + '/**/*.cc', recursive=True)]
    sim.source = cc_files

    headers = bld(features='ns3header')
    headers.module = 'SCION'

    # Find all .h and .hpp files
    header_files = [os.path.relpath(path, bld.path.abspath()) for path in glob.glob(model_dir + '/**/*.h', recursive=True)]
    headers.source = header_files

    obj = bld.create_ns3_program('scion', ['SCION', 'point-to-point'])
    obj.source = 'scion.cc'




