time_resolution: NS
topology: topology/5_geo_rel.xml
output: out/baseline_results.txt
simulation_duration: 105min
NUM_CORE: 128
beacon_service:
  policy: baseline
  #br_br_energy_file: out/br_br_energy.txt
  write_beacons_directory: out/
  period: 10min
  expiration_period: 6h
  first_beaconing: 0min
  last_beaconing: 100min
post_eval:
  - func: PrintAllDiscoveredPaths
  - func: PrintNoBeaconsPerInterfacePerDstOrOpt