time_resolution: NS
topology: topology/500_geo_rel_on_demand_lat_one_group.xml
output: out/baseline_results.txt
simulation_duration: 370min
NUM_CORE: 128
beacon_service:
  policy: diversity_age_based
  #br_br_energy_file: out/br_br_energy.txt
  write_beacons_directory: out/
  period: 10min
  expiration_period: 6h
  first_beaconing: 0min
  last_beaconing: 360min
post_eval:
  - func: PrintAllDiscoveredPaths
  - func: PrintNoBeaconsPerInterfacePerDstOrOpt