#!/usr/bin/env python3
import argparse
import datetime
import gc
import hashlib
import itertools
import pickle
import matplotlib.pyplot as plt
from matplotlib import gridspec
import json
import os

import numpy as np

from config import DEFAULT_FLOW_NUMBERS, DEFAULT_SCENARIO_TYPES, STARTUP_PHASE_SECONDS


def parse_args():
    parser = argparse.ArgumentParser(prog="SCION simulator host QOE plotter",
                                     description="Plotting of host QOE simulation results from SCION simulator")
    parser.add_argument(
        "filepath", help="Input file (result file of simulation) to parse")
    parser.add_argument("-l", "--loss", action='store_true', help="Plot the loss")
    parser.add_argument("-d", "--latency", action='store_true', help="Plot the latency")
    parser.add_argument("-t", "--total", action='store_true', help="Plot the total send rate of all flows combined")
    parser.add_argument("-g", "--gradient",
                        action="store_true", help="Plot the GCC gradient")
    parser.add_argument("-p", "--paths",
                        action="store_true", help="Plot the active paths")
    parser.add_argument("-s", "--state", action="store_true",
                        help="Plot the GCC state")
    parser.add_argument("-a", "--active-flows", action="store_true",
                        help="Plot the number of active flows")
    parser.add_argument("--latex", action="store_true",
                        help="Output the plot in LaTeX format")
    parser.add_argument("--avg", type=int, default=1,
                        help="Average every n values together")
    parser.add_argument("--mean", action="store_true",
                        help="Plot the mean latency")
    parser.add_argument("--std-dev", action="store_true",
                        help="Plot the standard deviation of the latency")
    parser.add_argument("--min-share", action="store_true",
                        help="Plot the minimum share")
    parser.add_argument("--total-received", action="store_true",
                        help="Plot the total bytes received (sent & acked)")
    parser.add_argument("--start-time", type=int, default=STARTUP_PHASE_SECONDS,
                        help=f"Plot data from this time onward (default: {STARTUP_PHASE_SECONDS})")
    parser.add_argument("--no-cache", action="store_true",
                        help="Do not use cached results")
    return parser.parse_args()


def _generate_cache_filename(files: list[str]) -> str:
    """
    Generate a unique filename for caching based on the input parameters.

    Parameters:
    - files: List of files to include in the cache filename.

    Returns:
    - cache_filename: Generated cache filename.
    """
    # Create a unique key based on the input parameters
    key = (tuple(files))
    # Generate a hash of the key
    key_hash = hashlib.md5(str(key).encode()).hexdigest()
    # Create a filename using the hash
    cache_filename = f'cache_{key_hash}.pkl'
    return cache_filename


def _get_state_attr_list(app: dict, attribute: str):
    states = app['states']
    return [state[attribute] for state in states]


def _latex_escape_label(label):
    label = label.replace('TcpCubic', 'TCP')
    label = label.replace('TcpNewReno', 'TCP')
    label = label.replace('#', '\\#')  # Escape characters for LaTeX
    return label


def latex_plot_header(label: str):
    print(f"\n% {label} (Generated by plot.py, {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')})")


def latex_plot(x: list, y: list, label: str, header: str, sharp=False):
    if not args.latex:
        return
    latex_plot_header(f"{label} - {header}")
    coordinates = ' '.join([f'({round(xi, 2)},{round(yi, 2)})' for xi, yi in zip(x, y) if xi is not None and yi is not None])
    extra_args = ", sharp plot" if sharp else ""
    print(f"\\addplot+[label={_latex_escape_label(label)}{extra_args}] coordinates {{{coordinates}}};")


def latex_boxplot(data, label):
    if not args.latex:
        return
    data = np.array(data)
    median = np.median(data)
    upper_quartile = np.percentile(data, 75)
    lower_quartile = np.percentile(data, 25)

    # https://en.wikipedia.org/wiki/Box_plot#Whiskers
    iqr = upper_quartile - lower_quartile
    upper_whisker = data[data <= upper_quartile + 1.5 * iqr].max()
    lower_whisker = data[data >= lower_quartile - 1.5 * iqr].min()

    latex_plot_header(label)
    print(f"\\addplot+[\n"
          f"    fill,\n"
          f"    fill opacity=0.7,\n"
          f"    draw=linecolor_before,\n"
          f"    thick,\n"
          f"    boxplot prepared={{\n"
          f"        median={median},\n"
          f"        upper quartile={upper_quartile},\n"
          f"        lower quartile={lower_quartile},\n"
          f"        upper whisker={upper_whisker},\n"
          f"        lower whisker={lower_whisker},\n"
          f"    }},\n"
          f"] coordinates {{}};")


def latex_plot_errorbar(x, y, yerr, label):
    if not args.latex:
        return

    latex_plot_header(label)
    print("\\addplot+[error bars/.cd, y dir=both, y explicit] coordinates {")
    for xi, yi, yerri in zip(x, y, yerr):
        print(f"({xi},{yi}) +- (0,{yerri})")
    print("};")


def plot_single_scenario(scenario: dict):
    """
    Plot single scenario results vs time
    """

    # max number of apps before we stop showing the legend
    max_apps_legend = 10

    plot_loss = args.loss
    plot_latency = args.latency
    plot_total_send_rate = args.total
    plot_active_paths = args.paths
    plot_gcc_gradient = args.gradient
    plot_gcc_state = args.state
    plot_gcc_params = False
    plot_active_flows = args.active_flows

    # For which app to plot extra details if there are multiple applications
    detail_app = 0

    no_plots = 1
    size_y = 1
    ratios = [1]

    # Lazy hack to make plot sizing dynamic
    for var in list(locals()):
        if var.startswith('plot_') and locals()[var]:
            no_plots += 1
            size_y += 1
            ratios.append(1)

    fig = plt.figure(figsize=(16, 9))
    plot_number = 0
    gs = gridspec.GridSpec(no_plots, 1, height_ratios=ratios)

    apps = scenario['apps']
    timestamps = scenario['timestamps']

    lines_dict = dict()

    def on_pick(event):
        legend_text = None
        # Check if the pick event is on the legend text
        if event.artist in legend.get_texts():
            legend_text = event.artist.get_text()
        # Check if the pick event is on the legend line
        elif event.artist in legend.get_lines():
            line_index = legend.get_lines().index(event.artist)
            legend_text = legend.get_texts()[line_index].get_text()

        if legend_text:
            # Find the original lines associated with this legend entry
            origlines = lines_dict.get(legend_text, [])
            if origlines:
                visibility = origlines[0].get_visible()
                for origline in origlines:
                    origline.set_visible(not visibility)
                plt.gcf().canvas.draw()

    fig.canvas.mpl_connect('pick_event', on_pick)

    ax = None

    if plot_loss:
        if ax is None:
            ax = plt.subplot(gs[plot_number])
        else:
            plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1
        for app in apps:
            plt.plot(app['time'], app['loss'], label=app['name'])

        if args.latex:
            print("\nLaTeX Loss:")
            for app in apps:
                latex_plot(app['time'], app['loss'], label=app['name'], header="Loss")
        if len(apps) <= max_apps_legend:
            plt.legend()
        plt.ylabel("Loss [%]")

    if plot_latency:
        if ax is None:
            ax = plt.subplot(gs[plot_number])
        else:
            plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1
        for app in apps:
            plt.plot(app['time'], app['latency'], label=app['name'])

        if args.latex:
            print("\nLaTeX Latency:")
            for app in apps:
                latex_plot(app['time'], app['latency'], label=app['name'], header="Latency")

        if len(apps) <= max_apps_legend:
            plt.legend()
        plt.ylabel("Latency [ms]")

    if ax is None:
        ax = plt.subplot(gs[plot_number])
    else:
        plt.subplot(gs[plot_number], sharex=ax)
    plot_number += 1
    if len(apps) == 1:  # If there is only one application, plot everything for it
        app = apps[0]
        plt.plot(app['time'], app['sendrate'],
                 label=app['name'], linewidth=1.5)
        if 'A_s' in app:
            plt.plot(app['time'], app['A_s'], label="A_s")
        if 'A_r' in app:
            plt.plot(app['time'], app['A_r'], label="A_r")
        plt.plot(app['time'], app['bottleneck_share'], label="fair share",
                 linewidth=0.5, color='black', linestyle='--')
        print(f"Median send rate:        {np.median(app['sendrate'])}")
    else:
        # Plot the sending rate for all applications
        for app in apps:
            lines = ()
            line_sendrate, = plt.plot(app['time'], app['sendrate'], label=app['name'], picker=5)
            lines += (line_sendrate,)
            # Plot bottleneck share and transition rates without a label to exclude them from the legend
            if 'bottleneck_share' in app:
                line_fair_share, = plt.plot(app['time'], app['bottleneck_share'], linewidth=0.5, color='black', linestyle='--', picker=5)
                # if not the detail app, hide the fair share line
                if app['name'] != apps[detail_app]['name']:
                    line_fair_share.set_visible(False)
                lines += (line_fair_share,)
            if 'oldrate' in app:
                line_oldrate, = plt.plot(app['time_transition'], app['oldrate'], linewidth=0.5, color='red', linestyle=':', picker=5)
                line_oldrate.set_visible(False)
                lines += (line_oldrate,)
            if 'newrate' in app:
                line_newrate, = plt.plot(app['time_transition'], app['newrate'], linewidth=0.5, color='blue', linestyle='-.', picker=5)
                line_newrate.set_visible(False)
                lines += (line_newrate,)

            # Store references to the lines for toggling
            lines_dict[app['name']] = lines

        if args.latex:
            print("\nLaTeX Sendrate:")
            for app in apps:
                latex_plot(app['time'], app['sendrate'], label=app['name'], header="Send Rate")

        # Print highest median send rate
        highest_median = 0
        highest_median_app = ""
        lowest_median = 1000
        lowest_median_app = ""
        for app in apps:
            median = np.median(app['sendrate'])
            if median > highest_median:
                highest_median = median
                highest_median_app = app['name']
            if median < lowest_median:
                lowest_median = median
                lowest_median_app = app['name']
        print(f"Highest median send rate: {highest_median} by app {highest_median_app})")
        print(f"Lowest median send rate:  {lowest_median} by app {lowest_median_app})")
    # Draw a gridline through 0
    plt.axhline(y=0, color='black', linewidth=0.5, linestyle='--')
    if len(apps) <= max_apps_legend:
        legend = plt.legend()
        # Make legend entries pickable
        for legline, origline in zip(legend.get_lines(), legend.get_texts()):
            legline.set_picker(5)  # 5 pts tolerance
            origline.set_picker(5)  # Also make the text pickable
    plt.ylabel("Send rate [MB/s]")

    if plot_total_send_rate:
        plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1

        # Get times and total send rates as list, sendrates are keyed under ['total_sendrate']
        times = list(timestamps.keys())
        sendrates = [r['total_sendrate'] for r in timestamps.values()]

        plt.plot(times, sendrates, label="Total send rate")
        plt.axhline(y=0, color='black', linewidth=0.5, linestyle='--')

        # Draw some lines for reference. Since all links are 1MB/s, a simple
        # upper bound for the total min(no_apps, no_paths)
        upper_bound = min(len(apps), max(apps[0]['active_path']) + 1)

        if upper_bound < max(sendrates) * 1.5 and upper_bound > 0.5 * max(sendrates):
            plt.axhline(y=upper_bound, color='black', linewidth=0.5, linestyle='--', label="Upper bound")

        print(f"Max total send rate:     {max(sendrates)}")
        print(f"Median total send rate:  {np.median(sendrates)}")
        print(f"Mean total send rate:    {np.mean(sendrates)}")

        if len(apps) <= max_apps_legend:
            plt.legend()
        plt.legend()
        plt.ylabel("Total Send Rate [MB/s]")

        if args.latex:
            print("\nLaTeX Combined Sendrate:")
            latex_plot(times, sendrates, label=app['name'], header="Total Send Rate")

    if plot_active_paths:
        plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1
        for i, app in enumerate(apps):
            dodge_height = 0.2 / len(apps)
            paths_dodged = [p + i * dodge_height for p in app['active_path']]
            plt.plot(app['time'], paths_dodged, label=app['name'])

        if len(apps) <= max_apps_legend:
            plt.legend()
        plt.ylabel("Paths")

        # Show only whole number ticks
        plt.yticks(range(max([max(app['active_path']) for app in apps]) + 1))

        if args.latex:
            print("\nLaTeX Active Paths:")
            for app in apps:
                latex_plot(app['time'], app['active_path'], label=app['name'], header="Active Path", sharp=True)

    if plot_gcc_state:
        plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1
        app = apps[detail_app]
        plt.plot(app['time'], app['gcc_state'], label="State",
                 drawstyle='steps-post', linestyle='--', linewidth=1)
        # plt.plot(app['time'], app['gcc_signal'], label="Signal",
        #          drawstyle='steps-post', linestyle='-.', linewidth=1)
        if len(apps) <= max_apps_legend:
            plt.legend()
        plt.ylabel("GCC State")

    if plot_gcc_gradient:
        plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1
        app = apps[detail_app]
        plt.plot(app['time'], app['gradient'], label="Gradient",
                 color='red', linestyle='-', linewidth=1)
        plt.plot(app['time'], app['threshold_hi'], label="threshold γ",
                 color='black', linestyle=':', linewidth=0.5)
        plt.plot(app['time'], app['threshold_lo'], label="threshold -γ",
                 color='black', linestyle=':', linewidth=0.5)
        if len(apps) <= max_apps_legend:
            plt.legend()
        plt.ylabel("GCC Gradient")

    if plot_gcc_params:
        plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1
        app = apps[detail_app]
        plt.plot(app['time'], app['kalman_gain'], label="Kalman gain",
                 color='red', linestyle='-', linewidth=1)
        plt.plot(app['time'], app['variance'], label="Variance",
                 color='green', linestyle='--', linewidth=1)
        plt.plot(app['time'], app['error'], label="Error",
                 color='black', linestyle=':', linewidth=1)

        if len(apps) <= max_apps_legend:
            plt.legend()
        plt.ylabel("GCC Parameters")

    if plot_active_flows:
        plt.subplot(gs[plot_number], sharex=ax)
        plot_number += 1

        plt.plot(list(timestamps.keys()), [r['active_apps'] for r in timestamps.values()], label="Active flows")
        plt.ylabel("Active flows")

    xlabel = "Time (s)"
    plt.xlabel(xlabel)

    settings = scenario['settings']

    if 'time_slots' in settings:
        # show vertical grid lines at time slots
        for i in range(1, settings['time_slots']):
            plt.axvline(x=i * settings['slot_size'], color='gray', linestyle='--', linewidth=0.5)

    plt.show()


def process_multi_scenario(scenarios: list[dict]):
    # Map containing the global results per flow type, per number of flows
    global_results = {}

    # Pre-add the 4 main types of results to maintain a constistent order
    for flow_type in DEFAULT_SCENARIO_TYPES:
        global_results[flow_type] = {}

    # Process only for these number of flows
    selected_flow_nums = DEFAULT_FLOW_NUMBERS

    # Pre-process all scenarios by grouping all data by flow type and number of flows
    for scenario in scenarios:
        # Use description as flow type
        flow_type = scenario['settings']['description']
        if flow_type not in global_results:
            global_results[flow_type] = {}

        num_flows = scenario['settings']['num_flows']

        # Uncomment to process only for selected flow numbers
        # if num_flows not in selected_flow_nums:
        #     continue

        if num_flows not in global_results[flow_type]:
            global_results[flow_type][num_flows] = {}

        # Select all of apps that are our target flows
        apps = [app for app in scenario['apps'] if app['traffic_type'] == 'target']

        # Median of the total sendrate throughout the entire simulation
        if 'median_total_sendrates' not in global_results[flow_type][num_flows]:
            global_results[flow_type][num_flows]['median_total_sendrates'] = []
        global_results[flow_type][num_flows]['median_total_sendrates'].append(scenario['median_total_sendrate'])

        # Compute the sum of the average bandwidths of each flow
        # The avg bandwidth is computed as the total bytes received divided by the total running time
        if 'cumulative_avg_bandwidths' not in global_results[flow_type][num_flows]:
            global_results[flow_type][num_flows]['cumulative_avg_bandwidths'] = []
        cumulative_avg_bandwidth = sum([app['average_bandwidth'] for app in apps])
        global_results[flow_type][num_flows]['cumulative_avg_bandwidths'].append(cumulative_avg_bandwidth)

        # Compute the minimum share as the minimum avg sendrate of each (flow,timeslot) pair
        # The values per timeslots are computed during individual simulation output processing
        if 'min_shares' not in global_results[flow_type][num_flows]:
            global_results[flow_type][num_flows]['min_shares'] = []
        min_share = float('inf')
        for slot, results in scenario['time_slots'].items():
            if results['mean_sendrate'] < min_share:
                min_share = results['mean_sendrate']
        global_results[flow_type][num_flows]['min_shares'].append(min_share)

        # # Lists containing loss/latency piled up over all flows AND all iterations
        # # Up to n are averaged together (within a flow). Override using the --avg n argument
        # if 'all_losses' not in global_results[flow_type][num_flows]:
        #     global_results[flow_type][num_flows]['all_losses'] = []
        # if 'all_latencies' not in global_results[flow_type][num_flows]:
        #     global_results[flow_type][num_flows]['all_latencies'] = []
        # all_losses = []
        # all_latencies = []
        # for app in apps:
        #     # To remove noise, consider only the averages across some interval for loss and latency
        #     # Since the actual values are recorded in 50ms intervals internally, we we average
        #     # 6 values together to get the values within a 300ms interval. Override with --avg n
        #     if args.avg > 1:
        #         # If --avg was used, we already average the values in the individual results parsing
        #         average_num = 1
        #     else:
        #         average_num = 6

        #     if args.loss:
        #         losses = app['loss']
        #         averaged_losses = [np.mean(losses[i:i+average_num]) for i in range(0, len(losses), average_num)]
        #         all_losses.extend(averaged_losses)

        #     if args.latency:
        #         latencies = app['latency']
        #         averaged_latencies = [np.mean(latencies[i:i+average_num]) for i in range(0, len(latencies), average_num)]
        #         all_latencies.extend(averaged_latencies)

        # # NOTE: Extend, not append, this is simply a flat list
        # global_results[flow_type][num_flows]['all_losses'].extend(all_losses)
        # global_results[flow_type][num_flows]['all_latencies'].extend(all_latencies)

        if 'total_loss_percentages' not in global_results[flow_type][num_flows]:
            global_results[flow_type][num_flows]['total_loss_percentages'] = []
        # List of loss percentages for each flow
        # The loss for each flow is the percentage of (bytes_lost / bytes_sent)
        loss_percs = []
        for app in apps:
            if 'total_loss_percentage' in app:
                loss_percs.append(app['total_loss_percentage'])
        global_results[flow_type][num_flows]['total_loss_percentages'].extend(loss_percs)

        if 'latencies_mean' not in global_results[flow_type][num_flows]:
            global_results[flow_type][num_flows]['latencies_mean'] = []
        if 'latencies_stddev' not in global_results[flow_type][num_flows]:
            global_results[flow_type][num_flows]['latencies_stddev'] = []
        lats_avg = []
        lats_stddev = []
        for app in apps:
            lats_avg.append(np.mean(app['latency']))
            lats_stddev.append(np.std(app['latency']))
        global_results[flow_type][num_flows]['latencies_mean'].extend(lats_avg)
        global_results[flow_type][num_flows]['latencies_stddev'].extend(lats_stddev)

        if 'total_bytes_received' not in global_results[flow_type][num_flows]:
            global_results[flow_type][num_flows]['total_bytes_received'] = []
        # List of total bytes received for each flow
        tot = [app['bytes_received'] for app in apps]
        global_results[flow_type][num_flows]['total_bytes_received'].append(tot)

    # Compute the mean and the 95% confidence interval of all medians of the total send rates per flow type and per number of flows
    for flow_type, flow_results in global_results.items():
        for num_flows, results in flow_results.items():
            results['mean_total_rcv'] = np.mean(results['total_bytes_received'])
            results['ci_total_rcv'] = 1.96 * np.std(results['total_bytes_received'], ddof=1) / np.sqrt(len(results['total_bytes_received']))

            results['mean_min_shares'] = np.mean(results['min_shares'])
            results['ci_min_shares'] = 1.96 * np.std(results['min_shares'], ddof=1) / np.sqrt(len(results['min_shares']))

            results['mean_cum_avg_bw'] = np.mean(results['cumulative_avg_bandwidths'])
            results['ci_cum_avg_bw'] = 1.96 * np.std(results['cumulative_avg_bandwidths'], ddof=1) / np.sqrt(len(results['cumulative_avg_bandwidths']))

            # Alternative where we use the mean of the medians of total sendrate in every time slot
            # results['mean_total'] = np.mean(results['median_total_sendrates'])
            # results['ci_total'] = 1.96 * np.std(results['median_total_sendrates'], ddof=1) / np.sqrt(len(results['median_total_sendrates']))

    # Clean up keys again, in case we didn't use the usual types
    global_results = {k: v for k, v in global_results.items() if v}
    return global_results


def plot_multi_scenario(global_results: dict) -> None:
    fig, ax = plt.subplots(figsize=(10, 6))

    # Create a mapping from original x values to evenly spaced integers
    flow_types = list(global_results.keys())
    all_flow_nums = sorted(global_results[flow_types[0]].keys())
    x_mapping = {num_flows: i * len(all_flow_nums) for i, num_flows in enumerate(all_flow_nums)}

    markers = itertools.cycle(['o', 's', '^', 'D', 'v', '<', '>', 'p', '*', 'h'])
    colors = itertools.cycle(plt.cm.tab10(np.linspace(0, 1, len(global_results))))

    ax.set_xlabel("# of Flows", fontsize=14)

    # Calculate dodge positions to avoid overlap of the boxes
    dodge_width = 0.9
    total_dodge_space = 1.0

    # Use the highest number of flows for the boxplots
    num_flows_for_boxplot = len(all_flow_nums) - 1

    # Boxplot for loss or latency
    if args.loss or args.latency:
        if args.loss:
            label = "Loss (%)"
        else:
            label = "Latency (ms)"
            if args.mean:
                label = "Mean " + label
            elif args.std_dev:
                label = "Std Dev " + label
        ax.set_ylabel(label, fontsize=14)

        for i, (flow_type, color, marker) in enumerate(zip(flow_types, colors, markers)):
            num_flows = sorted(global_results[flow_type].keys())

            if args.loss:
                data = [global_results[flow_type][n]['total_loss_percentages'] for n in num_flows]
            elif args.mean:
                data = [global_results[flow_type][n]['latencies_mean'] for n in num_flows]
            elif args.std_dev:
                data = [global_results[flow_type][n]['latencies_stddev'] for n in num_flows]

            dodge_positions = [x_mapping[n] + (i - len(flow_types)/2) * total_dodge_space for n in num_flows]

            ax.boxplot(data, positions=dodge_positions, widths=dodge_width, showfliers=False, patch_artist=True,
                       boxprops=dict(facecolor=color, color=color), medianprops=dict(color='black'),
                       whiskerprops=dict(color=color), capprops=dict(color=color))

            ax.plot([], label=flow_type, color=color, marker=marker, markersize=8, linewidth=2)

            if args.latex:
                latex_boxplot(data[num_flows_for_boxplot], label=flow_type)

        # Map the x ticks back to the original values because the box plots are juggled around
        ax.set_xticks(list(x_mapping.values()))
        ax.set_xticklabels(list(x_mapping.keys()))

    else:  # Errorbar plot for CumAvgBw, MinShare, or TotalReceived
        if args.total_received:
            label = "Total Received (B)"
        elif args.min_share:
            label = "Minimum Share (MB/s)"
        else:
            label = "Cum Avg Bandwidth (MB/s)"
        ax.set_ylabel(label, fontsize=14)

        for i, ((flow_type, color, marker), flow_results) in enumerate(zip(zip(global_results.keys(), colors, markers), global_results.values())):
            num_flows = sorted(flow_results.keys())

            if args.total_received:
                mean = [flow_results[n]['mean_total_rcv'] for n in num_flows]
                ci = [flow_results[n]['ci_total_rcv'] for n in num_flows]
            elif args.min_share:
                mean = [flow_results[n]['mean_min_shares'] for n in num_flows]
                ci = [flow_results[n]['ci_min_shares'] for n in num_flows]
            else:
                mean = [flow_results[n]['mean_cum_avg_bw'] for n in num_flows]
                ci = [flow_results[n]['ci_cum_avg_bw'] for n in num_flows]

            dodge_width = total_dodge_space / (len(global_results) + 1)
            dodge_positions = [n + (i - len(global_results)/2) * dodge_width for n in num_flows]

            ax.errorbar(dodge_positions, mean, yerr=ci, label=flow_type, color=color, marker=marker, markersize=8, linewidth=2, capsize=5)

            if args.latex:
                latex_plot_errorbar(num_flows, mean, ci, label=flow_type)

        ax.set_xticks(all_flow_nums)

    ax.grid(True, which='both', linestyle='--', linewidth=0.5)

    ax.tick_params(axis='both', which='major', labelsize=12)

    # Render the legend above the plot with a shadow and a frame
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), fancybox=True, shadow=True, ncol=3, fontsize=12)

    plt.tight_layout()  # Adjust the layout to make room for the legend

    plt.show()


def parse_simulation_results(file, inputs: dict) -> dict:
    """
    Parse the results from the simulation output file

    Returns a dictionary containing the parsed results

    This also requires the inputs file to get the traffic types and the
    simulation settings like time slot information, which the simulation itself
    is unaware of.
    """
    apps = []
    while (True):
        line = file.readline().strip()
        if "End Apps evaluation" in line:
            break
        elif "Host at" in line:
            host_tokens = line.split(' ')
            host = host_tokens[2]
        elif "{" in line:
            app = json.loads(line)
            app['host'] = host
            # print(f"Found results for host {host} app {
            #       app['app_id']} type {app['app_type']}")

            if 'states' not in app or app['states'] is None:
                print(f"    No states found for app {app['app_id']}")
                print(json.dumps(app, indent=4))
                continue

            # Select only states from args.start_time onwards
            app['states'] = [state for state in app['states'] if state['time'] >= args.start_time * 1000]

            # Remove startup from time and convert to seconds
            app['time'] = [state['time'] / 1000 -
                           args.start_time for state in app['states']]

            # Convert loss to percentage
            app['loss'] = [state['loss'] * 100 for state in app['states']]

            # Optional metrics for path transitions
            if 'in_transition' in app['states'][0]:
                app['oldrate'] = []
                app['newrate'] = []
                app['time_transition'] = []
                for i, state in enumerate(app['states']):
                    if state['in_transition']:
                        app['oldrate'].append(state['oldrate'])
                        app['newrate'].append(state['newrate'])
                        app['time_transition'].append(app['time'][i])
                    else:
                        app['oldrate'].append(None)
                        app['newrate'].append(None)
                        app['time_transition'].append(None)

            # For ever other field in states, generate a list of values
            for field in app['states'][0]:
                if field not in app:
                    app[field] = _get_state_attr_list(app, field)

            if args.avg > 1:
                for field in ['sendrate', 'loss', 'latency']:
                    # Average args.avg many values together
                    app[field] = [np.mean(app[field][i:i + args.avg])
                                  for i in range(0, len(app[field]), args.avg)]
                app['time'] = [app['time'][i] for i in range(0, len(app['time']), args.avg)]
                app['active_path'] = [app['active_path'][i] for i in range(0, len(app['active_path']), args.avg)]
                if 'bottleneck_share' in app:
                    app['bottleneck_share'] = [app['bottleneck_share'][i] for i in range(0, len(app['bottleneck_share']), args.avg)]

            if not 'name' in app:
                app['name'] = f"{app['app_type']}#{app['app_id']} "

            #     print(f"    Bytes sent:     {app['bytes_sent']}")
            #     print(f"    Bytes received: {app['bytes_received']}")

            app['total_running_time'] = app['time'][-1] - app['time'][0]
            app['average_bandwidth'] = app['bytes_received'] / app['total_running_time'] / 1e6

            app['bytes_lost'] = app['bytes_sent'] - app['bytes_received']
            if app['bytes_sent'] > 0:
                app['total_loss_percentage'] = app['bytes_lost'] / app['bytes_sent'] * 100
            else:
                print(f"App {app['name']} has 0 bytes sent")

            apps.append(app)

    if len(apps) == 0:
        print(f"No app results found in {file.name}")
        return {}
    else:
        print(f"Loaded {len(apps):2} apps from {file.name}")

    # Pre-process a dict with total sendrate and number of active apps at any point in time
    timestamps = {}
    for app in apps:
        for state in app['states']:
            t = state['time']
            if t not in timestamps:
                timestamps[t] = {'active_apps': 0, 'total_sendrate': 0}

            # if (state['sendrate'] == 0):
            #     continue

            timestamps[t]['active_apps'] += 1
            timestamps[t]['total_sendrate'] += state['sendrate']

    median_total_sendrate = np.median([r['total_sendrate'] for r in timestamps.values()])

    timestamps = {t / 1000 - args.start_time: r for t, r in timestamps.items()}
    timestamps = dict(sorted(timestamps.items()))

    settings = {}
    time_slots = {}

    if inputs is not None:
        # Copy traffic type (target or background) from input file, because
        # simulation is unaware of it, and so is its output
        for app, app_input in zip(
                sorted(apps, key=lambda x: x['app_id']),
                inputs['applications']
        ):
            if app['app_id'] != app_input['app_id']:
                print(f"App ID mismatch: {app['app_id']} vs {app_input['app_id']}")
                exit(1)

            if 'traffic_type' in app_input:
                app['traffic_type'] = app_input['traffic_type']

        if 'settings' in inputs:
            settings = inputs['settings']

            time_slots = {}
            for t, r in timestamps.items():
                slot = int(t // settings['slot_size'])
                if slot not in time_slots:
                    time_slots[slot] = {}
                if 'total_sendrates' not in time_slots[slot]:
                    time_slots[slot]['total_sendrates'] = []
                time_slots[slot]['total_sendrates'].append(r['total_sendrate'])

            for slot, results in time_slots.items():
                time_slots[slot]['median_total_sendrate'] = np.median(results['total_sendrates'])

            # For each app, sum up the average sendrate in every time slot
            for app in apps:
                for t, s in zip(app['time'], app['sendrate']):
                    slot = int(t // settings['slot_size'])
                    if 'sendrate' not in time_slots[slot]:
                        time_slots[slot]['sendrate'] = []
                    time_slots[slot]['sendrate'].append(s)
            for slot, results in time_slots.items():
                time_slots[slot]['median_sendrate'] = np.median(results['sendrate'])
                time_slots[slot]['mean_sendrate'] = np.mean(results['sendrate'])
    else:
        print("Some processing skipped due to missing inputs file")

    # Erase the states to save memory
    for app in apps:
        del app['states']

    scenario = {
        'apps': apps,
        'timestamps': timestamps,
        'time_slots': time_slots,
        'median_total_sendrate': median_total_sendrate,
        'settings': settings,
    }

    return scenario


def parse(paths: list[str]) -> list[dict]:
    scenarios = []
    cnt = 0
    for filepath in paths:
        # First, load the corresponding inputs file to get meta information like time slots
        inputs_json_path = filepath.replace(".out.txt", ".json")
        # try to load inputs
        inputs = None
        try:
            with open(inputs_json_path) as inputs_file:
                inputs = json.load(inputs_file)
        except:
            print(f"Could not find inputs file {inputs_json_path}")

        # Then, load the app metrics from the simulation output file
        with open(filepath) as file:
            while True:
                line = file.readline()
                if line == '':
                    break
                if "# Host Apps evaluation" in line:
                    s = parse_simulation_results(file, inputs)
                    if s:
                        scenarios.append(s)
        cnt += 1
        if cnt % 1000 == 0:
            print(f"Processed {cnt} files out of {len(paths)}")
            gc.collect()

    print("Processed a total of", len(scenarios), "scenarios")

    return scenarios


def main():
    global args

    args = parse_args()
    paths = []
    if os.path.isdir(args.filepath):
        for file in os.listdir(args.filepath):
            if file.endswith(".out.txt"):
                paths.append(os.path.join(args.filepath, file))
    else:
        paths.append(args.filepath)

    print(f"Found {len(paths)} files")

    if len(paths) == 1:
        scenarios = parse(paths)
        plot_single_scenario(scenarios[0])
    elif len(paths) > 1:
        cache_filename = _generate_cache_filename(paths)
        cache_filepath = os.path.join(args.filepath, cache_filename)
        if args.no_cache or not os.path.exists(cache_filepath):
            scenarios = parse(paths)
            global_results = process_multi_scenario(scenarios)
            print(f"Caching results to {cache_filepath}")
            with open(cache_filepath, 'wb') as f:
                pickle.dump(global_results, f)

        else:
            print(f"Loading cached results from {cache_filepath}")
            with open(cache_filepath, 'rb') as f:
                global_results = pickle.load(f)
        plot_multi_scenario(global_results)

    print("Done. Exiting.")


main()
